//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskAutomator.Tfs2015.Tests.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskAutomator.Tfs2015.Tests.Data.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;На карточке компаний из СПАРК должна появиться кнопка &amp;quot;Закрепить&amp;quot; с функционалом создания заявки на первичное закрепление. При сохранении такой заявки должен создаваться клиент (глобальная и локальная карточка) и устанавливаться связь со СПАРК. Только для головной организации (ГО). Филиалы ГО не копируются в КП. Меппинг полей СПАРК на теги set_client - в аттаче.&lt;/p&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;&lt;p&gt;[Васечкина С. 28.05.18]:&lt;/p&gt;&lt;p&gt;Если процедуры обновления данных в CRM выполняются с ошибкой или не выполняются, то эт [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string After_1 {
            get {
                return ResourceManager.GetString("After_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;На карточке компаний из СПАРК должна появиться кнопка &amp;quot;Закрепить&amp;quot; с функционалом создания заявки на первичное закрепление. При сохранении такой заявки должен создаваться клиент (глобальная и локальная карточка) и устанавливаться связь со СПАРК. Только для головной организации (ГО). Филиалы ГО не копируются в КП. Меппинг полей СПАРК на теги set_client - в аттаче.&lt;/p&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;&lt;p&gt;[Васечкина С. 28.05.18]:&lt;/p&gt;&lt;p&gt;Если процедуры обновления данных в CRM выполняются с ошибкой или не выполняются, то эт [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Before_1 {
            get {
                return ResourceManager.GetString("Before_1", resourceCulture);
            }
        }
    }
}
